#architecture
architecture:
  resnet50:
    name: resnet50
    weights: IMAGENET1K_V2

#optimizer
optimizer:
  SGD:
    name: SGD
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0001
  Adam:
    name: Adam
    lr: 0.05

#lrのscheduler
scheduler:
  cosineannealing:
    name: CosineAnnealingLR


test:
  # - はシーケンス（配列・リスト）
  - a:
    name: a
  - b:
    name: b
  - c:
    name: c
