#architecture
architecture:
  ResNet50:
    name: resnet50
    weights: IMAGENET1K_V2   # resnet50のデフォルトweight
  AlexNet:
    name: alexnet
    weights: IMAGENET1K_V1   # AlexNetのデフォルトweight
  vgg16:
    name: vgg16
    weights: IMAGENET1K_V1

#optimizer
optimizer:
  SGD:
    name: SGD
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0001
  Adam:
    name: Adam
    lr: 0.05
  Adagrad:
    name: Adagrad

#lrのscheduler
scheduler:
  cosineannealing:
    name: CosineAnnealingLR
  StepLR:
    name: StepLR
  ExponentialLR:
    name: ExponentialLR


test:
  # - はシーケンス（配列・リスト）
  - a:
    name: a
  - b:
    name: b
  - c:
    name: c
